added KMP linear pattern searching algorithm
GeorgiSamardzhiev/baron pull request #1
Opened 2019-07-11 16:52 UTC by sashodada

Айде да пробваме с PR-и как ше се справим 😆

2019-07-11 19:31 UTC, GeorgiSamardzhiev requested changes

2019-07-11 19:31 UTC, GeorgiSamardzhiev commented on patterns.cpp
> +        while (i < strlen(text)) {
Shouldn't strlen(text) be outside of the while condition?

2019-07-11 19:31 UTC, GeorgiSamardzhiev commented on patterns.cpp
> +#include <vector>
Should separete in hpp and cpp files and add #ifndef #define part, so one could include the file more than once.

2019-07-11 19:36 UTC, GeorgiSamardzhiev requested changes
I will add big gitignore file.

2019-07-11 19:36 UTC, GeorgiSamardzhiev commented on .gitignore
> +*.o
There will be a bigger gitignore file in future commits we don't need that now.

2019-08-08 12:35 UTC, sashodada commented
ша мърджаме ли 🗡?

2019-08-15 15:09 UTC, merged